### PR TITLE
Feature: global hotkeys

### PR DESCRIPTION
**Pull request by mtavkhelidze**
## Description ##

This enables global hotkeys while application is running for starting and Pomodoro timer.

## Discussion ##

I was thinking of adding another two hotkeys for long and short breaks, but decided not to do it at this point for two reasons:

- **_Four_** global hotkeys seem too much  
- Break start/stop might become redundant if we implement automatic pomodoro/break cycle in the future (which is in my plans anyway)

## Testing ##

MVTHotkey is covered by tests alright, the rest is not.

### CODE REVIEW

**Comment by dvntucker** [comment]
Hi @mtavkhelidze, thanks for the significant contribution. I've set this to the Release 1.2 milestone.

Just FYI, I have a PR in the works to enable automatic break/pomodor start (which I call continuous mode). I'm thinking of including it for 1.2 as well.

**Comment by dvntucker** [comment]
@mtavkhelidze a couple minor issues with this pull request:

* I notice you have personal copyrights in the new files. I'm OK with that, and it's technically OK according to a license like Apache 2.0, but could you put the Apache license header in the new files similar to the old files? 

* For consistency's sake, could you change the prefix of your new files from MVT to TY? I know TY technically should be a 3 letter prefix, but I'd like to keep the code consistent.

Sorry for the hassle and thanks again for the contribution.

**Comment by mtavkhelidze** [comment]
Hi Devon,

Fixed as per your request.

**NB** In the last commit message it should read "Fix `TYPreferencesTests`...". Not enough coffee this morning... :)

**Comment by dvntucker** [comment]
Thanks @mtavkhelidze. My plan is to start a contributors list in the readme, so I'll be sure to add you there.

**Comment by mtavkhelidze** [comment]
Cool. Thanks!

**Comment by dvntucker** [comment]
Hi @mtavkhelidze, this has been merged. I did some small changes with the UI in order to merge it with existing changes.

If you have time, it'd be nice be able to either disable hotkeys completely or to clear the hotkey itself. For changes like these I think it's nice to have the option to disable them for users that don't want them. If you don't have time for it, no worries ;) It'll be something I look into when I have time. Cheers.

**Comment by mtavkhelidze** [comment]
Hi @dvntucker ,

I think logical would be to add enable/disable flag.

In UI something like this:

capture d ecran 2016-09-17 a 09 48 02

If you think that would be ok, I could do that.

**Pull request merged**
