### PR TITLE
Added preference for pomodoros per cycle

### PR DESCRIPTION
**Pull request by tmgriffiths**
I've added an extra parameter to the preferences for controlling the pomodoro cycle. The value sets the number of pomodoros before switching to a long break. This value is used in the if-statemets with `pomodoroCount` and `newCount` in `TYDefaultTomighty.m` instead of the original default 4. I've also added the default number of 4 to this in `TyUserDefaultsPreferences.m`

I've built and packaged it up with `build.sh` and `package.sh`. These are not a part of the repo though, do I submit them elsewhere or will the maintainer update these? I have incremented the version number to 1.3 in `package.sh`

---

**Changes**
- Added `PREF_TIME_CYCLE` constant to set the number of pomodoros in a
cycle before giving a long break.

- Added extra text field to the preferences window to accomodate this.

- Changed name of tab from `Time` to `Timing`

- Changed code in `TYDefaultTomighty.m` to  compare `pomodoroCount` to the
int `pomodoroCycle` instead of "4".

- Changed code in `TYDefaultTomighty.m` to  compare `newCount` to the
int `pomodoroCycle` instead of "4".

- Added a default value of 4 pomodoros per cyle

- Incremented version number to 1.3

### CODE REVIEW

**Comment by dvntucker** [comment]
Fantastic, thank you. I'll check it out ASAP and hopefully get a release out this weekend.

**Comment by dvntucker** [comment]
As for the built artifacts, I will update those. They are handled on the Github releases page.

**Comment by tmgriffiths** [comment]
I just cleaned up the all the sections of the preference window a bit. I'm not a UI expert or a designer, but i aligned some baselines and centred some things here and there. I think it looks better.

**Comment by dvntucker** [comment]
Merged. I'm working on a new release, but unfortunately xcodebuild has changed and there are some issues with the build now that need to be worked through. I'll let you know when a new release is up. Cheers.

**Pull request merged**
